### ISSUE TITLE
Design a self-evaluation process

### ISSUE THREAD

**Issue by waldoj** [ustaxcourt/ato#2]
The vendor's scrum team should be able to assess tasks to determine whether they present a security risk, and the Court's technical lead should be able to do likewise, so that 

## Tasks
- [x] look at [Slack's SDL](https://slack.engineering/moving-fast-and-securing-things-540e6c5ae58a), which is a good candidate for emulation
- [x] put together the text for the self-evaluation
- [x] house the self-evaluation in a place convenient for those who need to use it

## Acceptance Criteria
- [x] the security reviewer is satisfied that the risk threshold is acceptable
- [x] the intended users understand how to use the self-evaluation
- [x] the intended users are happy with where the self-evaluation is located

**Comment by waldoj** [comment]
We put this into place a couple of months ago. Thus far, it seems to be working well.
